version: '3.7'

services:
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: 0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py rqworker default"
    environment:
      DEBUG: 0
    volumes:
      - .:/app
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reliability
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest

volumes:
  pgdata:
